apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-servico
  namespace: trabalho-sis-dis
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - trabalho-sis-dis
    labelSelectors:
      app: servico
  duration: "30s"
